server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.81:3306/dyna?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dyna
    password: J5QxGkWNyF72EBHH
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.31.81
      port: 6379
      password: jhkdjhkjdhsIUTYURTU_Qt23iy
      database: 0

mybatis:
  mapper-locations: classpath:mapper/setting/*.xml
  type-aliases-package: com.dyna.modules.setting.entity
